language: java
jdk:
  - openjdk8

branches:
  only:
    - master

before_install:
  - chmod +x gradlew

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
  - zip -r lngg-springboot2-webservice *
  - mkdir -p deploy
  - mv lngg-springboot-webservice.zip deploy/lngg-springboot2-webservice.zip

deploy:
  - provider: s3
    access_key_id: $WAS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $WAS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: lngg-springboot-build # S3 버킷
    region: ap-northeast-2
    skip_cleanup: true
    acl: private # zip 파일 접근을 private으로
    local_dir: deploy # before_deploy에서 생성한 디텍토리
    wait-until-deployed: true

# CI 실행 완료 시 메일로 알림
notifications:
  email:
    recipients:
      - leejy0978@naver.com